Apr-19 09h42: run, tag, installation.md, ...

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -9,29 +9,7 @@ fi
 # paths
 # =====================
 
-get_dir() {
-   local -r first_dir="$1"
-   local -r second_dir="$2"
-   local -r useless_folder="${first_dir}/useless"
-   local folder
-   mkdir -p "$useless_folder" 2>/dev/null \
-      && folder="$first_dir" \
-      || folder="$second_dir"
-   rm -r "$useless_folder" 2>/dev/null
-   echo "$folder"
-}
-
-get_source_dir() {
-   get_dir "/opt/navi" "${HOME}/.navi/src"
-}
-
-get_bin_dir() {
-   get_dir "/usr/bin" "/usr/local/bin"
-}
-
-get_tmp_dir() {
-   get_dir "/tmp/navi" "${HOME}/.navi/tmp"
-}
+export BIN_DIR="${BIN_DIR:-"${HOME}/.cargo/bin"}"
 
 
 # =====================
@@ -81,7 +59,7 @@ log::ansi() {
 _log() {
    local template="$1"
    shift
-   echoerr -e "$(printf "$template" "$@")"
+   echoerr "$(printf "$template" "$@")"
 }
 
 _header() {
@@ -113,19 +91,19 @@ die() {
 }
 
 no_binary_warning() {
-   echoerr "There's no precompiled binary for your platform: $(uname -a)"
+   log::note "There's no precompiled binary for your platform: $(uname -a)"
 }
 
 installation_finish_instructions() {
    local -r shell="$(get_shell)"
-   echoerr -e "Finished. To call navi, restart your shell or reload the config file:\n   source ~/.${shell}rc"
+   log::note -e "Finished. To call navi, restart your shell or reload the config file:\n   source ~/.${shell}rc"
    local code
    if [[ "$shell" == "zsh" ]]; then
       code="navi widget ${shell} | source"
    else
       code='source <(navi widget '"$shell"')'
    fi
-   echoerr -e "\nTo add the Ctrl-G keybinding, add the following to ~/.${shell}rc:\n   ${code}"
+   log::note -e "\nTo add the Ctrl-G keybinding, add the following to ~/.${shell}rc:\n   ${code}"
 }
 
 
@@ -141,7 +119,7 @@ sha256() {
    elif command_exists openssl; then
       openssl dgst -sha256
    else
-      echoerr "Unable to calculate sha256!"
+      log::note "Unable to calculate sha256!"
       exit 43
    fi
 }
@@ -169,20 +147,24 @@ asset_url() {
 }
 
 download_asset() {
+   local -r tmp_dir="$(mktemp -d -t navi-install-XXXX)"
    local -r url="$(asset_url "$@")"
-   mkdir -p "$TMP_DIR"
-   cd "$TMP_DIR"
-   rm -f navi.tar.gz
-   echoerr "Downloading ${url}..."
+   log::note "Downloading ${url}..."
+   cd "$tmp_dir"
    curl -L "$url" -o navi.tar.gz
    tar xvzf navi.tar.gz
-   rm -f navi.tar.gz
-   cp "${TMP_DIR}/navi" "${BIN_DIR}/navi"
+   mkdir -p "${BIN_DIR}" &>/dev/null || true
+   mv "./navi" "${BIN_DIR}/navi"
 }
 
 sha_for_asset_on_github() {
    local -r url="$(asset_url "$@")"
    curl -sL "$url" | sha256 | awk '{print $1}'
+}
+
+error_installing() {
+      log::error "Unable to install navi. Please check https://github.com/denisidoro/navi for alternative installation instructions"
+      exit 33
 }
 
 
@@ -211,16 +193,13 @@ command_exists() {
 get_target() {
    local -r unamea="$(uname -a)"
    local -r archi="$(uname -sm)"
-   local is_android
-
-   [[ $unamea = *Android* ]] && is_android=true || is_android=false
 
    local target
-   case "$archi" in
-      Darwin*) target="x86_64-apple-darwin" ;;
-      *x86*) $is_android && target="" || target="x86_64-unknown-linux-musl" ;;
-      *aarch*) $is_android && target="aarch64-linux-android" || target="armv7-unknown-linux-musleabihf" ;;
-      *arm*) $is_android && target="armv7-linux-androideabi" || target="armv7-unknown-linux-musleabihf" ;;
+   case "$unamea $archi" in
+      *arwin*) target="x86_64-apple-darwin" ;;
+      *inux*x86*) target="x86_64-unknown-linux-musl" ;;
+      *ndroid*aarch*|*ndroid*arm*) target="aarch64-linux-android" ;;
+      *inux*aarch*|*inux*arm*) target="armv7-unknown-linux-musleabihf" ;;
       *) target="" ;;
    esac
 
@@ -237,35 +216,46 @@ get_shell() {
 # =====================
 
 install_navi() {
-   export SRC_DIR="${SRC_DIR:-"$(get_source_dir)"}"
-   export BIN_DIR="${BIN_DIR:-"$(get_bin_dir)"}"
-   export TMP_DIR="${TMP_DIR:-"$(get_tmp_dir)"}"
-   echoerr -e "Relevant directories:\n- src: ${SRC_DIR}\n- bin: ${BIN_DIR}\n- tmp: ${TMP_DIR}\n"
-
    local -r target="$(get_target)"
 
-   if [[ -n "$target" ]]; then
-      local -r version="$(latest_version_released)"
-      download_asset "$version" "$target"
+   if command_exists navi; then
+      log::success "navi is already installed"
+       exit 0
+
+   elif command_exists brew; then
+      brew install navi
 
    elif command_exists cargo; then
-      no_binary_warning
-      echoerr "Building sources..."
-      git clone https://github.com/denisidoro/navi "$SRC_DIR"
-      cd "$SRC_DIR"
-      make install
+      cargo install navi
+
+   elif [[ -n "$target" ]]; then
+      local -r version="$(latest_version_released)"
+      download_asset "$version" "$target" || error_installing
 
    else
-      no_binary_warning
-      echoerr "You don't have the necessary tools to build it"
-      echoerr "Please open an issue at https://github.com/denisidoro/navi"
-      echoerr "Aborting..."
-      exit 33
+      error_installing
+
    fi
 
-   local -r shell="$(get_shell)"
-   echoerr -e "Finished. To call navi, restart your shell or reload the config file:\n   source ~/.${shell}rc"
-   echoerr -e "\nTo add the Ctrl-G keybinding, add the following to ~/.${shell}rc:\n   source \"$(navi widget ${shell})\""
+   echoerr
+   log::success "Finished" 
+   log::success "navi is now available at ${BIN_DIR}/navi" 
+   echoerr
+
+   if echo "$PATH" | grep -q "$BIN_DIR"; then
+      :
+   else
+      echoerr
+      log::note 'Please add the following to your .bashrc-like file:'
+      echo -e '  export PATH="${PATH}:'"$BIN_DIR"'"\n'
+   fi
+
+   log::note "To call navi, restart your shell or reload your .bashrc-like config file"
+   echo
+   log::note "Check https://github.com/denisidoro/navi for more info"
+
+   export PATH="${PATH}:${BIN_DIR}"
+
    return 0
 }
 
